version: v3.0

allowlist:
  - name: "rt/*"
blocklist: []
builtin-topics: []

participants:

  - name: SimpleParticipantLocal
    kind: local
    domain: 0
    transport: udp

  - name: SimpleParticipantRemote
    kind: local
    domain: 0
    transport: udp
