version: v3.0

allowlist:
  - name: "rt/*"
blocklist: []
builtin-topics: []

participants:

  - name: SimpleParticipant
    kind: local
    domain: 0
    transport: udp

  - name: ServerDSParticipant
    kind: local-discovery-server
    discovery-server-guid:
      ros-discovery-server: true
      id: 0
    listening-addresses:
      - ip: 127.0.0.1
        port: 11811
        transport: udp
