version: v3.0

allowlist:
  - name: "rt/*"
blocklist:
builtin-topics:

participants:

  - name: SimpleParticipant
    kind: local
    domain: $ROS_DOMAIN_ID
    transport: udp

  - name: ServerDSParticipant
    kind: local-discovery-server
    discovery-server-guid:
      id: 200
    listening-addresses:
      - domain: $DS_HOSTNAME
        port: 11811
        transport: udp
