# Quick start
#
# 1st terminal:
# docker compose -f compose.talker.yaml up
# 
# 2nd terminal:
# export ROS_DOMAIN_ID=1
# ros2 run demo_nodes_cpp talker

services:

  talker:
    image: husarion/ros2-demo-nodes:humble
    network_mode: host
    ipc: host
    environment:
      - ROS_DOMAIN_ID=1
    command: ros2 run demo_nodes_cpp talker

  dds-router-talker:
    image: husarnet/dds-router:v2.0.0
    network_mode: host
    ipc: host
    volumes:
      - ./router-config.talker.yaml:/config.yaml
    environment:
      - AUTO_CONFIG=FALSE
    command: bash -c "ddsrouter -c /config.yaml -r 10"
