services:

  ros2router:
    build:
      context: ../../../
    network_mode: host
    volumes:
      - ../../../entrypoint.sh:/entrypoint.sh
      - ../../../config_daemon.sh:/config_daemon.sh
      - ../../../local-participant.yaml:/local-participant.yaml
    environment:
      # LOCAL_PARTICIPANT: |
      #   - name: SimpleParticipantLocal
      #     kind: local
      #     domain: 0
      #     transport: udp
      # # - ROS_LOCALHOST_ONLY=1 # use it with ROS 2 Humble
      # IGNORE_PARTICIPANTS_FLAGS: filter_different_host # use it with ROS 2 Iron
      USE_HUSARNET: FALSE
    entrypoint: tail -f /dev/null

# 1st Host (LAN only)
# docker compose up -d
# export ROS_LOCALHOST_ONLY=1
# ros2 run demo_nodes_cpp talker

# 2nd Host (LAN only)
# export ROS_LOCALHOST_ONLY=1
# ros2 run demo_nodes_cpp listener
