services:

  ds:
    image: husarnet/ros2router:1.2.0
    network_mode: host
    environment:
      - ROS_DISCOVERY_SERVER=rosbot2r:11811
      - DISCOVERY_SERVER_ID=10
      - WHITELIST_INTERFACES=172.29.0.1

  listener:
    image: husarion/ros2-demo-nodes:humble
    command: ros2 run demo_nodes_cpp listener

networks:
  default:
    ipam:
      config:
        - subnet: 172.29.0.0/24