version: v3.0

allowlist:
  
  - name: "*"

participants:

  - name: LocalParticipant
    kind: local
    domain: 0

  - name: RemoteParticipant
    kind: discovery-server
    discovery-server-guid:
      id: 1
      ros-discovery-server: true
    listening-addresses:
      - domain: my-talker
        port: 11811
        transport: udp