# Quick start
#
# docker compose pull
# docker compose up -d
# docker compose exec dds_router bash 

services:
  ros2router:
    build:
      context: ../
      dockerfile: Dockerfile
    network_mode: host
    ipc: host
    volumes:
      - ../config_daemon.sh:/config_daemon.sh
      - ../entrypoint.sh:/entrypoint.sh
      - ./filter.yaml:/filter.yaml
      - ./test2.sh:/test2.sh
      - ../config.discovery-server.template.yaml:/config.discovery-server.template.yaml
      - ../config.lan.template.yaml:/config.lan.template.yaml
      - ../config.wan.template.yaml:/config.wan.template.yaml
      - ../local-participant.yaml:/local-participant.yaml
    environment:
      ROS_DOMAIN_ID: 123
      ROS_DISCOVERY_SERVER: ";;;;rosbot2r:123"
      DISCOVERY_SERVER_LISTENING_PORT: "12345"
      DISCOVERY_SERVER_ID: 1
      ROS_NAMESPACE: robocik
      LOCAL_PARTICIPANT2: |
          - name: LocalParticipant
            kind: local
            domain: 0
            transport: udp
          - name: LocalDockerParticipant
            kind: local
            domain: 123
            transport: shm
      # FILTER: |
      #   allowlist:
      #     - name: "rt/chatter2"
      #       type: "std_msgs::msg::dds_::String_"
      #   blocklist:
      #     - name: "rt/rosout"
      #       type: "rcl_interfaces::msg::dds_::Log_"
      #   builtin-topics: []

      # - LOCAL_TRANSPORT=builtin
      # - EXIT_IF_HUSARNET_NOT_AVAILABLE=TRUE
      # - EXIT_IF_HOST_TABLE_CHANGED=TRUE
    entrypoint: sleep 3600