# Quick start
#
# docker compose pull
# docker compose up -d
# docker compose exec dds_router bash 

services:
  dds_router:
    image: husarnet/dds-router:local-participant-whitelist
    restart: always
    network_mode: host
    ipc: host
    volumes:
      - ../config.discovery-server.template.yaml:/config.discovery-server.template.yaml
      - ../config.wan.template.yaml:/config.wan.template.yaml
      - ../config.local.template.yaml:/config.local.template.yaml
      - ../config_daemon.sh:/config_daemon.sh
      - ../entrypoint.sh:/entrypoint.sh
      - ./filter.yaml:/filter.yaml
    environment:
      - ROS_DOMAIN_ID=123
      - ROS_DISCOVERY_SERVER="rosbot2r:123 [fc94:5fa1:c323:30bc:a87d:7485:23c4:f5a2]:9876"
      - DS_LISTENING_PORT="12345"
      - DS_ID="1 2 3"
      # - LOCAL_TRANSPORT=builtin
      # - EXIT_IF_HUSARNET_NOT_AVAILABLE=TRUE
      # - EXIT_IF_HOST_TABLE_CHANGED=TRUE
    entrypoint: sleep 3600