# Quick start
#
# docker compose pull
# docker compose up -d
# docker compose exec dds_router bash 

services:
  ros2router:
    build:
      context: ../
      dockerfile: Dockerfile
    network_mode: host
    ipc: host
    volumes:
      - ../config_daemon.sh:/config_daemon.sh
      - ../entrypoint.sh:/entrypoint.sh
      - ./filter.yaml:/filter.yaml
      - ./test2.sh:/test2.sh
    environment:
      ROS_DOMAIN_ID: 123
      ROS_DISCOVERY_SERVER: ";;;;rosbot2r:123;;;;[fc94:5fa1:c323:30bc:a87d:7485:23c4:f5a2]:9876"
      DISCOVERY_SERVER_LISTENING_PORT: "12345"
      DISCOVERY_SERVER_ID: 1
      # FILTER: |
      #   allowlist:
      #     - name: "rt/chatter2"
      #       type: "std_msgs::msg::dds_::String_"
      #   blocklist:
      #     - name: "rt/rosout"
      #       type: "rcl_interfaces::msg::dds_::Log_"
      #   builtin-topics: []

      # - LOCAL_TRANSPORT=builtin
      # - EXIT_IF_HUSARNET_NOT_AVAILABLE=TRUE
      # - EXIT_IF_HOST_TABLE_CHANGED=TRUE
    entrypoint: sleep 3600