services:

  ds:
    image: husarnet/ros2router:1.2.0
    network_mode: host
    ipc: host
    pid: host
    user: ${UID:-1000}:${GID:-1000}
    volumes:
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/shadow:/etc/shadow:ro
    environment:
      - LOCAL_TRANSPORT=builtin
      - ROS_DISCOVERY_SERVER=rosbot2r:11811
      - DISCOVERY_SERVER_ID=10
      # - ROS_LOCALHOST_ONLY=1 # use it with ROS 2 Humble
      - IGNORE_PARTICIPANTS_FLAGS=filter_different_host # use it with ROS 2 Iron
