services:

  ds:
    image: husarnet/ros2router:1.3.0
    network_mode: host
    ipc: host
    environment:
      - LOCAL_TRANSPORT=builtin
      - ROS_DISCOVERY_SERVER=rosbot2r:11811
      - DISCOVERY_SERVER_ID=10
      - ROS_LOCALHOST_ONLY=1

  talker:
    image: husarion/ros2-demo-nodes:humble
    network_mode: host
    ipc: host
    environment:
      - ROS_LOCALHOST_ONLY=1
    command: ros2 run demo_nodes_cpp listener
