services:

  ds:
    image: husarnet/ros2router:1.3.0
    network_mode: host
    environment:
      - ROS_DISCOVERY_SERVER=rosbot2r:11811
      - DISCOVERY_SERVER_ID=10
      # - ROS_LOCALHOST_ONLY=1 # use it with ROS 2 Humble
      - IGNORE_PARTICIPANTS_FLAGS=filter_different_host # use it with ROS 2 Iron
