services:

  ds:
    image: husarnet/ros2router:1.2.0
    network_mode: host
    environment:
      - ROS_DISCOVERY_SERVER=rosbot2r:11811
      - DISCOVERY_SERVER_ID=10
      - IGNORE_PARTICIPANTS_FLAGS=filter_different_host
