name: Build a Docker Image

on:
  push:
    branches:
      - 'experimental'
  
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      with:
        version: latest
    
    - name: Login to Docker Registry
      uses: docker/login-action@v1
      with:
        registry: docker.io
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
          
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile
        platforms: linux/amd64, linux/arm64
        push: true
        tags: husarnet/dds-router:experimental
        cache-from: type=registry,ref=husarnet/dds-router:experimental
        cache-to: type=inline
        # cache-from: type=registry,ref=husarnet/dds-router:buildcache
        # cache-to: type=registry,ref=husarnet/dds-router:buildcache,mode=max


