x-husarnet-net:
  &husarnet-net
  network_mode: service:husarnet-talker
  ipc: service:husarnet-talker

services:

  husarnet-talker:
    image: husarnet/husarnet:2.0.180
    ipc: shareable
    networks:
      - network_talker
    volumes:
      - /var/lib/husarnet
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      - HOSTNAME=talker
      - JOINCODE
      - HUSARNET_DEBUG=1

  # highlight-start
  ros2router-talker:
    image: husarnet/ros2router:1.3.0
    <<: *husarnet-net
    environment:
      - LOCAL_TRANSPORT=builtin
      - DISCOVERY_SERVER_LISTENING_PORT=11811
      - DISCOVERY_SERVER_ID=0
  # highlight-end

  talker:
    image: husarion/ros2-demo-nodes:humble
    <<: *husarnet-net
    command: ros2 run demo_nodes_cpp talker

networks:
  network_talker:
    driver: bridge