x-husarnet-net:
  &husarnet-net
  network_mode: service:husarnet-listener
  ipc: service:husarnet-listener

services:

  husarnet-listener:
    image: husarnet/husarnet:2.0.180
    ipc: shareable
    networks:
      - network_listener
    volumes:
      - /var/lib/husarnet
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      - HOSTNAME=listener
      - JOINCODE
      - HUSARNET_DEBUG=1
      - WAIT_HOSTNAMES=talker

  # highlight-start
  ros2router-listener:
    image: husarnet/ros2router:1.3.0
    <<: *husarnet-net
    depends_on: 
      husarnet-listener: { condition: service_healthy }
    environment:
      - LOCAL_TRANSPORT=builtin
      - ROS_DISCOVERY_SERVER=talker:11811
      - DISCOVERY_SERVER_ID=10
  # highlight-end

  listener:
    image: husarion/ros2-demo-nodes:humble
    <<: *husarnet-net
    command: ros2 run demo_nodes_cpp listener

networks:
  network_listener:
    driver: bridge